apiVersion: batch/v1
kind: Job
metadata:
  name: csv-processor
spec:
  template:
    spec:
      containers:
      - name: processor
        image: mini-processor
        command: ["python", "process.py"]
      restartPolicy: Never
