name: Check and Build API (Python)

on:
  push:
    branches:
      - dev
      - homolog
      - production
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ github.repository }}-${{ github.ref_name }}
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./api
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint/Test (opcional)
        working-directory: ./api
        run: |
          . venv/bin/activate
          pip install pytest
          pytest || echo "Testes falharam"

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f Dockerfile.api .