name: Check and Build API (Python)

on:
  push:
    branches:
      - dev
      - homolog
      - production
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # ou ajuste para a sua versão

      - name: Install dependencies
        working-directory: ./api
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lint/Test (opcional)
        working-directory: ./api
        run: |
          . venv/bin/activate
          # Roda lint e test se existirem
          if [ -f "pytest.ini" ] || [ -d "tests" ]; then
            pip install pytest
            pytest || echo "Testes falharam"
          fi
          if [ -f "pyproject.toml" ]; then
            pip install ruff || true
            ruff check . || echo "Lint falhou"
          fi

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }} -f Dockerfile.api .
