name: Check, Build, Push and Deploy (API)

on:
  push:
    branches:
      - dev
      - homolog
      - production
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: raiosystems

    env:
      IMAGE_NAME: ${{ github.repository }}-${{ github.ref_name }}
      IMAGE_TAG: latest
      CURRENT_BRANCH: ${{ github.ref_name }}

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      # - name: Install dependencies
      #   working-directory: ./api
      #   run: |
      #     python -m venv venv
      #     . venv/bin/activate
      #     pip install --upgrade pip
      #     pip install -r requirements.txt

      # - name: Run Lint/Test (opcional)
      #   working-directory: ./api
      #   run: |
      #     . venv/bin/activate
      #     pip install pytest
      #     pytest || echo "Testes falharam"

      # - name: Log in to GitHub Container Registry
      #   run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # - name: Build Docker image
      #   run: |
      #     docker build -t ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f Dockerfile.api .

      # - name: Push Docker image
      #   run: |
      #     docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      ### 🌱 Terraform Deploy ###
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Terraform Init
        working-directory: ./terraform/k8s/${{ env.CURRENT_BRANCH }}
        run: terraform init

      # - name: Terraform Plan
      #   working-directory: ./terraform/k8s/${{ env.CURRENT_BRANCH }}
      #   run: terraform plan -var="current_branch=${{ env.CURRENT_BRANCH }}"

      - name: Terraform Apply
        working-directory: ./terraform/k8s/${{ env.CURRENT_BRANCH }}
        run: terraform apply -auto-approve -var="current_branch=${{ env.CURRENT_BRANCH }}"
